Javascript best practices
JonahKayizzi/Javascript-Best-Practices-TO-DO-list-app pull request #1
Opened 2022-10-03 19:16 UTC by JonahKayizzi

The purpose of this pull request is to;

- Give feedback on someone else's project based on clean code best practices.

- Apply knowledge the student has gained in the past when giving a code review.

- Perform a simple code review for a coding partner.

- Understand existing code in a way that allows the student to give a good code review

2022-10-04 12:32 UTC, Shedrack-Sunday requested changes
Hello @JonahKayizzi!

Good job on the project so far 👏 

Highlights of proper work 📝 
✔️ Good README file
✔️ proper use of modules
✔️ No Linter errors

However, there are a few changes I suggest you make to make the project follow the javascript best practices. 👨‍🎓 .

Please see them as pointed out in the review. 
Tag me @shedrackSunday, to know if you need clearity

2022-10-04 12:32 UTC, Shedrack-Sunday commented on src/modules/populateTasks.js
> +    const taskElement = createHTMLElement('li', 'task-item', 'task-item', '', tasksContainer);
Just as I mentioned above, I think it would be clean to declare the variables at the top most part of the code, then use them inside whatever scope you choose.

2022-10-04 12:32 UTC, Shedrack-Sunday commented on src/modules/createHTMLelement.js
> +};
To avoid repeating yourself, you can declare the `element` as global once, use it in your code for proper modularity, and follow the KISS best practices.

2022-10-04 12:32 UTC, Shedrack-Sunday commented on src/index.js
> +  }
I think you can optimise this decisdion logic with the _Short-circuit Evaluation _  method, to return the `myTaskList.tasks = storedTasks;` . that will keep the code simple. :)

2022-10-04 15:10 UTC, JonahKayizzi commented on src/modules/populateTasks.js
> +    const taskElement = createHTMLElement('li', 'task-item', 'task-item', '', tasksContainer);
Hello @Shedrack-Sunday, thanks for the suggestion. I will effect the change for the global scope variables. The majority of the variables though are block scope and moving them to the top may result into bugs.

2022-10-04 15:11 UTC, JonahKayizzi commented on src/modules/createHTMLelement.js
> +};
Thanks @Shedrack-Sunday for the suggestion. This is to be effected. I am also considering making use of spread arguments to change it into one method.

2022-10-04 15:12 UTC, JonahKayizzi commented on src/index.js
> +  }
Thanks @Shedrack-Sunday, this is going to be adopted.

2022-10-04 15:14 UTC, Shedrack-Sunday commented on src/modules/populateTasks.js
> +    const taskElement = createHTMLElement('li', 'task-item', 'task-item', '', tasksContainer);
Rightly noted. Please make the changes of those which can be declared above for clarity and modularity. 
Good job 👋

2022-10-04 15:15 UTC, Shedrack-Sunday commented on src/modules/createHTMLelement.js
> +};
That would be great. Please do make the changes and let's merge it. Good job 👍

2022-10-05 16:46 UTC, Shedrack-Sunday approved these changes
Hello @JonahKayizzi  👋 

Good job on making the changes.  There's nothing else to add, you can now merge the pull request and move on to the next 🎊 .

Highlight of Work!!
✅ Good Readme
✅ proper use of Javascript practices 
✔️ No linter errors.

2022-10-05 16:50 UTC, merged